config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  resources :events do
  	resources :attandances
    resources :event_pictures, only: [:create]
  end
  	
  resources :users, except: [:new, :create, :index] do
  	resources :avatars, only: [:create]
  end
  resources :charges
  root "events#index"

  namespace :admins do
    resources :users, :events, :attandances, :pending_validations
    root 'admins#index'
  end
end

app/controllers/admins/pending_validations_controller.rb
class Admins::PendingValidationsController < ApplicationController
  def index
  	@events = Event.all
  end

  def create
  @event = Event.find(params[:format])
  	if @event.update(validated: false)
  		flash.now[:success] = 'Event validated'
  		redirect_to admins_pending_validations_path
  	else
  		flash.now[:error] = 'Rate'
  		render :index
  	end
  end

  def show
  end

  def edit
  end

  def update
  	@event = Event.find(params[:id])
  	if @event.update(validated: true)
  		flash.now[:success] = 'Event validated'
  		redirect_to admins_pending_validations_path
  	else
  		flash.now[:error] = 'Rate'
  		render :index
  	end
  end
end

app/helpers/admins/pending_validations_helper.rb
module Admins::PendingValidationsHelper
end

app/views/admins/pending_validations/edit.html.erb
<h1>Admins::PendingValidations#edit</h1>
<p>Find me in app/views/admins/pending_validations/edit.html.erb</p>

app/views/admins/pending_validations/index.html.erb
                              <h2>Pending validations :</h2>
                              <div class="table-responsive">
                                   <table class="table table-striped table-sm">
                                        <thead>
                                             <tr>
                                                  <th>#</th>
                                                  <th>Title</th>
                                                  <th>Start date</th>
                                                  <th>Price</th>
                                                  <th>Users</th>
                                                  <th>Attandances</th>
                                                  <th>Edit</th>
                                                  <th>Delete</th>
                                                  <th>Validate</th>

                                             </tr>
                                        </thead>
                                        <tbody>
                                        <% @events.each do |event| %>
                                             <% if event.validated.nil? %>        
                                               <tr>
                                                  <td><%= event.id %></td>
                                                  <td><%= event.title %></td>
                                                  <td><%= event.date %></td>
                                                  <td><%= event.price %></td>
                                                  <% if event.attandances.exists? %>
                                                       <td><%= event.attandances.size %></td>
                                                       <td><%= link_to 'voir', admins_attandance_path(event.id), class: "btn btn-sm btn-primary btn-block" %></td>
                                                  <% else %>                                      
                                                       <td></td>     
                                                       <td></td>     
                                                  <% end %> 
                                                       <td><%= link_to "Edit", edit_admins_event_path(event.id), class: "btn btn-sm btn-primary btn-block" %></td>
                                                       <td><%= button_to "Delete", event_path(event.id), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-sm btn-danger btn-block" %></td>    
                                                  <td><%= button_to "Validate", admins_pending_validation_path(event.id), data: { confirm: "Are you sure?" }, method: :put, class: "btn btn-sm btn-success btn-block" %><%= button_to "Unvalidate", admins_pending_validations_path(event.id), data: { confirm: "Are you sure?" }, method: :post, class: "btn btn-sm btn-success btn-block" %></td>
                                                </tr>                                       
                                             <% end %>     
                                        <% end %>                                                                  
                                        </tbody>
                                   </table>
                              </div>                   

               <h2>Refused :</h2>
                              <div class="table-responsive">
                                   <table class="table table-striped table-sm">
                                        <thead>
                                             <tr>
                                                  <th>#</th>
                                                  <th>Title</th>
                                                  <th>Start date</th>
                                                  <th>Price</th>
                                                  <th>Users</th>
                                                  <th>Attandances</th>
                                                  <th>Edit</th>
                                                  <th>Delete</th>
                                                  <th>Validate</th>

                                             </tr>
                                        </thead>
                                        <tbody>
                                        <% @events.each do |event| %>
                                             <% if event.validated == false %>        
                                               <tr>
                                                  <td><%= event.id %></td>
                                                  <td><%= event.title %></td>
                                                  <td><%= event.date %></td>
                                                  <td><%= event.price %></td>
                                                  <% if event.attandances.exists? %>
                                                       <td><%= event.attandances.size %></td>
                                                       <td><%= link_to 'voir', admins_attandance_path(event.id), class: "btn btn-sm btn-primary btn-block" %></td>
                                                  <% else %>
                                                       <td></td>     
                                                       <td></td>     
                                                    
                                                  <% end %> 
                                                       <td><%= link_to "Edit", edit_admins_event_path(event.id), class: "btn btn-sm btn-primary btn-block" %></td>
                                                       <td><%= button_to "Delete", event_path(event.id), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-sm btn-danger btn-block" %></td>    
                                                  <td><%= button_to "Validate", admins_pending_validation_path(event.id), data: { confirm: "Are you sure?" }, method: :put, class: "btn btn-sm btn-success btn-block" %></td>
                                                </tr>                                       
                                             <% end %>     
                                        <% end %>                                                                  
                                        </tbody>
                                   </table>
                              </div>                   
               <h2>Accepted :</h2>
                              <div class="table-responsive">
                                   <table class="table table-striped table-sm">
                                        <thead>
                                             <tr>
                                                  <th>#</th>
                                                  <th>Title</th>
                                                  <th>Start date</th>
                                                  <th>Price</th>
                                                  <th>Users</th>
                                                  <th>Attandances</th>
                                                  <th>Edit</th>
                                                  <th>Delete</th>
                                                  <th>Validate</th>

                                             </tr>
                                        </thead>
                                        <tbody>
                                        <% @events.each do |event| %>
                                             <% if event.validated %>        
                                               <tr>
                                                  <td><%= event.id %></td>
                                                  <td><%= event.title %></td>
                                                  <td><%= event.date %></td>
                                                  <td><%= event.price %></td>
                                                  <% if event.attandances.exists? %>
                                                       <td><%= event.attandances.size %></td>
                                                       <td><%= link_to 'voir', admins_attandance_path(event.id), class: "btn btn-sm btn-primary btn-block" %></td>
                                                  <% else %>
                                                 
                                                       <td></td>     
                                                       <td></td>     
                                                  <% end %> 
                                                       <td><%= link_to "Edit", edit_admins_event_path(event.id), class: "btn btn-sm btn-primary btn-block" %></td>
                                                       <td><%= button_to "Delete", event_path(event.id), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-sm btn-danger btn-block" %></td>    
                                                  <td><%= button_to "Unvalidate", admins_pending_validations_path(event.id), data: { confirm: "Are you sure?" }, method: :post, class: "btn btn-sm btn-success btn-block" %></td>
                                                </tr>                                       
                                             <% end %>     
                                        <% end %>                                                                  
                                        </tbody>
                                   </table>
                              </div>      

app/views/admins/pending_validations/show.html.erb
<h1>Admins::PendingValidations#show</h1>
<p>Find me in app/views/admins/pending_validations/show.html.erb</p>