config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  resources :events do
  	resources :attandances
    resources :event_pictures, only: [:create]
  end
  	
  resources :users, except: [:new, :create, :index] do
  	resources :avatars, only: [:create]
  end
  resources :charges
  root "events#index"

  namespace :admins do
    resources :users, :events, :attandances, :pending_validations
    root 'admins#index'
  end
end

app/models/attandance.rb
class Attandance < ApplicationRecord
	after_create :new_attandant

  belongs_to :user #participants as clasname user
  belongs_to :event

	validates :stripe_customer_id, presence: true

  def new_attandant
    AttandantMailer.new_attandant(self.event).deliver_now
  end
end

app/controllers/admins/attandances_controller.rb
class Admins::AttandancesController < ApplicationController
	before_action :authenticate_admin
	layout 'admins'
end

app/controllers/attandances_controller.rb
class AttandancesController < ApplicationController
	before_action :set_event, only: [:new, :create, :index]
	before_action :authenticate_user!
	before_action :is_not_your_event, only: [:index]

	def set_event
		@event = Event.find(params[:event_id])
  	@amount = @event.price * 100
	end

  def is_not_your_event
    unless @event.admin == current_user
      flash[:danger] = 'Back off ! Not your event !'
      redirect_to root_path
    end
  end

  def index
  end

  def new
  	@attandance = Attandance.new
  end

  def create
		@attandance = Attandance.new(user: current_user, event: @event)
  	
  	unless @event.is_free
	  	customer = Stripe::Customer.create(
		    :email => params[:stripeEmail],
		    :source  => params[:stripeToken]
		  )

		  charge = Stripe::Charge.create(
		    :customer    => customer.id,
		    :amount      => @amount,
		    :description => 'Rails Stripe customer',
		    :currency    => 'eur'
		  )
			@attandance.stripe_customer_id = charge.customer
		else
			@attandance.stripe_customer_id = 'freeevent'
		end

		if @attandance.save!
			flash[:success] = 'Reservation reussie !'
			# redirect_to event_path(@event.id)
		else
			flash[:error] = 'Erreur lors de la reservation'
			p @attandance.errors
			render :new
		end
		rescue Stripe::CardError => e
		  flash[:error] = e.message
		  redirect_to new_charge_path
	end
end

app/helpers/admins/attandances_helper.rb
module Admins::AttandancesHelper
end

app/helpers/attandances_helper.rb
module AttandancesHelper
end

app/views/attandances/create.html.erb
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <h2>Thanks, you paid <strong><%= @amount/100 %>$</strong>!</h2>
			        <p class='text-center'>Back to <%= link_to 'event', event_path(params[:event_id]) %></p>
            </div>
          </div>
        </div>
      </div>

app/views/attandances/index.html.erb
<div class="container text-center">    
    <div class="col-sm-8">
      <div class="row">
<!-- ---------------------------------------- AVATAR + NOM ----------------------- -->
		<% if @event.attandances.blank? %>
		    <div class="col-sm-12">
	          <div class="well">
	            <h2 class="h4 mb-3 font-weight-normal text-center">Aucun inscrit :(</h2><br>
	          
	            <hr class="my-0">
	          </div>
	        </div>

		<% else %>
	        <div class="col-sm-12">
	          <div class="panel panel-default">
	            <div class="panel-body">
		            <h2 class="h2 mb-3 font-weight-normal text-center"><%= @event.attandances.size %> inscrits :</h2>
	            </div>
	          </div>
	        </div>
		
			<% @event.attandances.map{|attandance| attandance.user}.each do |user| %>
		        <div class="col-sm-12">
		          <div class="well">
		            <h2 class="h4 mb-3 font-weight-normal text-center"><%= user.full_name %></h2>
		            <hr class="my-0">
		            <p class='text-center'><%= user.email %></p>
		            <hr class="my-0">
		          </div>
		        </div>
			<% end %>
		<% end %>
      </div>
    </div>

  	<div class="col-sm-4 well">
	      <div class="thumbnail">
	        <p><strong><%= @event.title %></strong></p>
	        <%if @event.event_picture.attached?%>
	        	<%= image_tag @event.event_picture, alt: 'Event pic', width: 400 %><br>
	        <%else%>
	       		<%= image_tag("img.png", width: 400, alt: "Lyon", class: "img-circle") %>
	        <p>=== Il n'y a pas encore de photo liée à cet event ===</p>
	        <% end %>
	        
	        
	        <%= link_to "Editer mon event", edit_event_path(@event.id), class: "btn btn-lg btn-primary btn-block" %><br>
			<hr>
			<h1 class="h3 mb-3 font-weight-normal text-center">Change your event's picture</h1>
			<%= form_tag event_event_pictures_path(@event), multipart: true do %>
				<%= file_field_tag :event_picture %><br>
				<%= submit_tag "Upload", class: "btn btn-lg btn-primary btn-block" %>
			<% end %>
			<hr>
	      </div>      
	</div>
</div>

app/views/attandances/new.html.erb
<% provide(:title, 'Reservation') %>


<div class="container text-center">    
    <div class="col-sm-12">
    
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <h2 class="h1 mb-3 font-weight-normal text-center"><%= @event.title %></h2>  
              <p><%= @event.location %>, Lyon, France</p>
            </div>
          </div>
        </div>
      </div>

      <div class="row mr-auto">
	        <div class="well">
	          	<div class="col-sm-8">
					<%if @event.event_picture.attached?%>
	                   <%= image_tag @event.event_picture, alt: 'Event pic', width: 400, class:'rounded' %>
	                <%else%>
	                   <%= image_tag("bird.jpg", alt: "Avatar") %>
	                    <p>=== Il n'y a pas encore de photo liée à cet event ===</p>
	                <% end %>	
				</div>
				<div class="col-sm-4">
			        <h2 class="h4 mb-3 font-weight-normal text-center"><%= @event.description %></h2><br>
			        <hr class="my-0">
			        <hr class="my-0"><br>
				    <p>Le <%= @event.date %> de <%= @event.hour %> a <%=@event.end_date_hour %></p>
				    <hr class="my-0">
				    <hr class="my-0"><br>
				    <p>Tarif : <%= @event.price %>€</p>
				    <hr class="my-0">
				    <hr class="my-0"><br>
				    <p>Organise par : <%= @event.admin.first_name %><br><%= @event.admin.email %></p>
				</div>
				<br>
				<% if @event.is_free %>
					<div class="col-sm-12 align-self-center">
						<hr>
						<div class='col-sm-3'>
						</div>
						<div class="col-sm-6">
					      <%= form_tag event_attandances_path do %>
						      <h1 class="h4 mb-3 font-weight-normal text-center">Attend this event</h1>
					      <%= button_to "Make a reservation", event_attandances_path, method: :create, class: "btn btn-lg btn-primary btn-block" %>
					      <%= link_to "Back", :back %><br><br><br>
							<% end %>
						</div>
					</div>
				<% else %>
					<% unless @event.attandances.find_by(event: @event, user: current_user) || @event.admin == current_user  %>
						<div class="col-sm-12">
							<h2 class="h4 mb-3 font-weight-normal text-center">Reservation pour 1 personne :</h2>  
							<%= form_tag event_attandances_path do %>
							<article>
								<% if flash[:error].present? %>
								<div id="error_explanation">
									<p><%= flash[:error] %></p>
								</div>
								<% end %>
								<label class="amount">
									<span>Amount: <%= @amount/100 %>$</span>
								</label>
							</article>

							<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
							data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
							data-description="Event entry"
							data-amount="<%= @amount %>"
							data-locale="auto"></script>
							<% end %><br>
							<%= link_to "Back", :back %><br><br><br>
						</div>
					<% else %>
					<p>Evenement deja reserve!</p>
					<% end %>
				<% end %>
	        </div>
	   </div> 
    </div>
</div>