config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  resources :events do
  	resources :attandances
    resources :event_pictures, only: [:create]
  end
  	
  resources :users, except: [:new, :create, :index] do
  	resources :avatars, only: [:create]
  end
  resources :charges
  root "events#index"

  namespace :admins do
    resources :users, :events, :attandances, :pending_validations
    root 'admins#index'
  end
end

app/models/user.rb
require 'open-uri'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  before_save :grab_image

  
	after_create :welcome_send

	has_many :attandances, dependent: :destroy
	has_many :events, through: :attandances
	has_many :events, foreign_key: 'admin_id', dependent: :destroy
  
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def full_name
    self.first_name + ' ' + self.last_name
  end

  def grab_image
    downloaded_image = (open('http://loremflickr.com/300/300/'))
    self.avatar.attach(io: downloaded_image, filename: 'image.png')
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin
	before_action :define_user, only: [:show, :edit, :update]
	layout 'admins'

  def define_user
    @user = User.find(params[:id])
  end

	def index
		@users = User.all
	end

	def show    
	end

	def edit
	end

	def update
    post_params = params.require(:user).permit(:first_name, :last_name, :description)

    if @user.update(post_params)
      flash[:success] = 'Profile updated'
      redirect_to admins_users_path
    else
      render :edit
    end
	end

	def destroy
    User.find(params[:id]).destroy
    flash[:danger] = 'User deleted'
    redirect_to admins_users_path
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:secret, :show]
  before_action :is_not_your_profile, only: [:show, :edit]
  before_action :define_user, only: [:show, :edit, :update]

  def define_user
    @user = User.find(params[:id])
  end

  def is_not_your_profile
    unless params[:id].to_i == current_user.id || current_user.is_admin
      flash[:danger] = 'Back off ! Not your profile !'
      redirect_to root_path
    end
  end

  def show
  end

  def edit
  end

  def update
    post_params = params.require(:user).permit(:first_name, :last_name, :description)

    if @user.update(post_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render :edit
    end
	end
	
  def secret
  end

    def destroy
    User.find(params[:id]).destroy
    flash[:danger] = 'User deleted'
    redirect_to admins_users_path
   end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/edit.html.erb
<% provide(:title, 'Edit my profile') %>
     <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">        
                <%= link_to 'Dashboard', admins_root_path, class:'nav-link active' %>
              </li>
              <li class="nav-item">        
                <%= link_to 'Users', admins_users_path, class:'nav-link active' %>
              </li>
              <li class="nav-item">        
                <%= link_to 'Events', admins_events_path, class:'nav-link active' %>
              </li>
              <li class="nav-item">        
                <%= link_to 'Resas', admins_attandances_path, class:'nav-link active'%>
              </li>
                              
                                <li class="nav-item">        
                                     <%= link_to 'Validations', admins_pending_validations_path, class:'nav-link active'%>
                                </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Saved reports</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Current month
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Last quarter
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Social engagement
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Year-end sale
                </a>
              </li>
            </ul>
          </div>
        </nav>


<% if @user.errors.any? %>
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading">Erreur!</h4>
  <p>Nous n'avons pas réussi à créer l'event pour la (ou les) raison(s) suivante(s) :</p>  
  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <hr>
  <p class="mb-0">Veuillez reesayer, suivre les consignes et rester patient.</p>
</div>

<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br>
      <%= form_for(@user) do |f| %>
      <h1 class="h3 mb-3 font-weight-normal text-center">Update your informations</h1>

      <div class="form-group">
        <%= f.label :first_name, 'Prenom' %><br />
        <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :last_name, 'Nom' %><br />
        <%= f.text_field :last_name, autofocus: true, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description, 'Description' %><br />
        <%= f.text_area :description, autofocus: true, size: '40x10', class: "form-control" %>
      </div>
              <li class="nav-item">        
          <%= link_to 'Validations', admins_pending_validations_path, class:'nav-link active'%>
        </li>

      <div class="actions mt-5">
        <%= f.submit "Update", class: "btn btn-lg btn-primary btn-block" %>
      </div>
      <br><br>
      <% end %>


      <h1 class="h3 mb-3 font-weight-normal text-center">Change your profile picture</h1>
      <%= form_tag user_avatars_path(@user), multipart: true do %>
        <%= file_field_tag :avatar, class: "btn btn-sm btn-primary btn-block" %><br>
        <%= submit_tag "Upload", class: "btn btn-lg btn-primary btn-block" %><br><br><br>
      <% end %>
    </div>
  </div>
</div>

</div>
</div>

app/views/admins/users/index.html.erb
     <div class="container-fluid">
     	<div class="row">
     		<nav class="col-md-2 d-none d-md-block bg-light sidebar">
     			<div class="sidebar-sticky">
     				<ul class="nav flex-column">
     					<li class="nav-item">        
     						<%= link_to 'Dashboard', admins_root_path, class:'nav-link active' %>
     					</li>
     					<li class="nav-item">        
     						<%= link_to 'Users', admins_users_path, class:'nav-link active' %>
     					</li>
     					<li class="nav-item">        
     						<%= link_to 'Events', admins_events_path, class:'nav-link active' %>
     					</li>
     					<li class="nav-item">        
     						<%= link_to 'Resas', admins_attandances_path, class:'nav-link active'%>
     					</li>
                              
                                <li class="nav-item">        
                                     <%= link_to 'Validations', admins_pending_validations_path, class:'nav-link active'%>
                                </li>
     				</ul>

     				<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
     					<span>Saved reports</span>
     					<a class="d-flex align-items-center text-muted" href="#">
     						<span data-feather="plus-circle"></span>
     					</a>
     				</h6>
     				<ul class="nav flex-column mb-2">
     					<li class="nav-item">
     						<a class="nav-link" href="#">
     							<span data-feather="file-text"></span>
     							Current month
     						</a>
     					</li>
     					<li class="nav-item">
     						<a class="nav-link" href="#">
     							<span data-feather="file-text"></span>
     							Last quarter
     						</a>
     					</li>
     					<li class="nav-item">
     						<a class="nav-link" href="#">
     							<span data-feather="file-text"></span>
     							Social engagement
     						</a>
     					</li>
     					<li class="nav-item">
     						<a class="nav-link" href="#">
     							<span data-feather="file-text"></span>
     							Year-end sale
     						</a>
     					</li>
     				</ul>
     			</div>
     		</nav>

     		<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
     			<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
     				<h1 class="h2">Dashboard</h1>
     				<div class="btn-toolbar mb-2 mb-md-0">
     					<div class="btn-group mr-2">
     						<button class="btn btn-sm btn-outline-secondary">Share</button>
     						<button class="btn btn-sm btn-outline-secondary">Export</button>
     					</div>
     					<button class="btn btn-sm btn-outline-secondary dropdown-toggle">
     						<span data-feather="calendar"></span>
     						This week
     					</button>
     				</div>
     			</div>



     			<h2>Users</h2>
     			<div class="table-responsive">
     				<table class="table table-striped table-sm">
     					<thead>
     						<tr>
     							<th>#</th>
     							<th>First name</th>
     							<th>Last_name</th>
     							<th>Email</th>
                                        <th>Event Admin</th>
                                        <th>Edit</th>
     							<th>Delete</th>
     						</tr>
     					</thead>

                         <% @users.each do |user| %>          
     					<tbody>
     						<tr>
                                        <td><%= user.id %></td>
                                        <td><%= user.first_name %></td>
                                        <td><%= user.last_name %></td>
                                        <td><%= user.email %></td>
     							<td><% if user.events.exists? %><%= link_to 'voir', admins_user_path(user.id), class: "btn btn-sm btn-primary btn-block" %><% end %></td>
                                        <td><%= link_to "Edit", edit_admins_user_path(user.id), class: "btn btn-sm btn-primary btn-block" %></td>
                                        <td><%= button_to "Delete", admins_user_path(user.id), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-sm btn-primary btn-block" %></td>				
     						</tr>     						
     					</tbody>
                         <% end %>     

     				</table>
     			</div>
     		</main>
     	</div>
     </div>

app/views/admins/users/show.html.erb
     <div class="container-fluid">
     	<div class="row">
     		<nav class="col-md-2 d-none d-md-block bg-light sidebar">
     			<div class="sidebar-sticky">
     				<ul class="nav flex-column">
     					<li class="nav-item">        
     						<%= link_to 'Dashboard', admins_root_path, class:'nav-link active' %>
     					</li>
     					<li class="nav-item">        
     						<%= link_to 'Users', admins_users_path, class:'nav-link active' %>
     					</li>
     					<li class="nav-item">        
     						<%= link_to 'Events', admins_events_path, class:'nav-link active' %>
     					</li>
     					<li class="nav-item">        
     						<%= link_to 'Resas', admins_attandances_path, class:'nav-link active'%>
     					</li>
                                <li class="nav-item">        
                                     <%= link_to 'Validations', admins_pending_validations_path, class:'nav-link active'%>
                                </li>
     				</ul>

     				<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
     					<span>Saved reports</span>
     					<a class="d-flex align-items-center text-muted" href="#">
     						<span data-feather="plus-circle"></span>
     					</a>
     				</h6>
     				<ul class="nav flex-column mb-2">
     					<li class="nav-item">
     						<a class="nav-link" href="#">
     							<span data-feather="file-text"></span>
     							Current month
     						</a>
     					</li>
     					<li class="nav-item">
     						<a class="nav-link" href="#">
     							<span data-feather="file-text"></span>
     							Last quarter
     						</a>
     					</li>
     					<li class="nav-item">
     						<a class="nav-link" href="#">
     							<span data-feather="file-text"></span>
     							Social engagement
     						</a>
     					</li>
     					<li class="nav-item">
     						<a class="nav-link" href="#">
     							<span data-feather="file-text"></span>
     							Year-end sale
     						</a>
     					</li>
     				</ul>
     			</div>
     		</nav>

     		<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
     			<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
     				<h1 class="h2">Dashboard</h1>
     				<div class="btn-toolbar mb-2 mb-md-0">
     					<div class="btn-group mr-2">
     						<button class="btn btn-sm btn-outline-secondary">Share</button>
     						<button class="btn btn-sm btn-outline-secondary">Export</button>
     					</div>
     					<button class="btn btn-sm btn-outline-secondary dropdown-toggle">
     						<span data-feather="calendar"></span>
     						This week

		     			<h2>Needing validations events :</h2>
		     			<div class="table-responsive">
		     				<table class="table table-striped table-sm">
		     					<thead>
		     						<tr>
		     							<th>#</th>
		     							<th>Title</th>
		     							<th>Start date</th>
		     							<th>Price</th>
		     							<th>Users</th>
		     							<th>Attandances</th>
		     							<th>Edit</th>
                                                  <th>Delete</th>
		     						</tr>
		     					</thead>
		     					<tbody>
		     					<% @user.events.each do |event| %>   
                                        <% unless event.validated %>       
		     						<tr>
		     							<td><%= event.id %></td>
		     							<td><%= event.title %></td>
                                                  <td><%= event.date %></td>
                                                  <td><%= event.price %></td>
                                                  <% if event.attandances.exists? %>
                                                       <td><%= event.attandances.size %></td>
                                                       <td><%= link_to 'voir', admins_attandance_path(event.id), class: "btn btn-sm btn-primary btn-block" %></td>
                                                       <td><%= link_to "Edit", edit_admins_event_path(event.id), class: "btn btn-sm btn-primary btn-block" %></td>
                                                       <td><%= button_to "Delete", event_path(event.id), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-sm btn-primary btn-block" %></td>             
                                                  <% end %> 
		     									     					</tbody>
                                        <% end %>     
		     					<% end %>     
		     				</table>
		     			</div>     			
     				</div>     			
     			</div>     			
     		</main>
     	</div>
     </div>