config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  resources :events do
  	resources :attandances
    resources :event_pictures, only: [:create]
  end
  	
  resources :users, except: [:new, :create, :index] do
  	resources :avatars, only: [:create]
  end
  resources :charges
  root "events#index"

  namespace :admins do
    resources :users, :events, :attandances, :pending_validations
    root 'admins#index'
  end
end

app/views/layouts/_events.html.erb
<div class="col-sm-2 well">
      <div class="thumbnail">
        <p>Upcoming Events:</p>
        <img src="paris.jpg" alt="Paris" width="400" height="300">
        <p><strong>Paris</strong></p>
        <p>Fri. 27 November 2015</p>
        <button class="btn btn-primary">Info</button>
      </div>      
      <div class="well">
        <p>ADS</p>
      </div>
      <div class="well">
        <p>ADS</p>
      </div>
</div>
  

app/views/layouts/_flashes.html.erb
<% flash.each do |name, msg| -%>
	<%= content_tag :div, msg, class: "alert alert-#{name}" %>
<% end -%>

app/views/layouts/_footer.html.erb
<footer class="container-fluid d-flex justify-content-between text-center fixed-bottom">
 <a class="text-muted" href="#">Back to top</a>
 <span class="text-muted">Made with love <i class="fab fa-angellist"></i> in Lyon</span>
</footer>

app/views/layouts/_head.html.erb
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

app/views/layouts/_header.html.erb
  <nav class="navbar sticky-top navbar-expand-lg navbar-dark">
  <%= link_to 'EventHack', root_path, class:"navbar-brand logo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Events', root_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to 'Create an event', new_event_path, class:'nav-link' %>
        <% else %>
          <%= link_to 'Create an event', new_event_path, class:'nav-link disabled' %>
        <% end %>
      </li>
      <% if current_user.exists? && current_user.is_admin %>
      <hr>
        <li class="nav-item">        
          <%= link_to 'Users', admins_users_path, class:'nav-link active' %>
        </li>
        <li class="nav-item">        
          <%= link_to 'Events', admins_events_path, class:'nav-link active' %>
        </li>
        <li class="nav-item">        
          <%= link_to 'Resas', admins_attandances_path, class:'nav-link active'%>
        </li>
        <li class="nav-item">        
          <%= link_to 'Validations', admins_pending_validations_path, class:'nav-link active'%>
        </li>
      <% end %>   
    </ul>
  <!-- ------------------------ DROPDOWN ACCOUNT ---------------   -->
    <div class="dropdown navbar-right">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="glyphicon glyphicon-user"></span> My Account
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <% if user_signed_in? %>
        <a class="dropdown-item" href="<%= user_path(current_user.id) %>">Mon profile</a>
        <%= link_to "Se deconnecter", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
      <% else %>
        <a class="dropdown-item" href="<%= new_user_session_path %>">Connection</a>
        <a class="dropdown-item" href="<%= new_user_registration_path %>">Inscription</a>
       <% end %> 
      </div>
    </div>

  </div>
</nav>

app/views/layouts/_header_admins.html.erb
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#">Sign out</a>
        </li>
      </ul>
    </nav>

app/views/layouts/_javascript.html.erb
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
	<script>
	  $(function () {
	    $(".dropdown-toggle").dropdown();
	  })
	</script>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
  <head>
     <%= render 'layouts/head' %>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header_admins' %>
  <%= render 'layouts/flashes' %>
  
  
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
  

    <%= render 'layouts/javascript' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <%= render 'layouts/head' %>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



  <%= render 'layouts/header' %>
  <%= render 'layouts/flashes' %>
    <%= yield %>

  

    <%= render 'layouts/footer' %>

  

    <%= render 'layouts/javascript' %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>